
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl TColliTransfer_Export
// ------------------------------
#ifndef TCOLLITRANSFER_EXPORT_EXPORT_H
#define TCOLLITRANSFER_EXPORT_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (TCOLLITRANSFER_EXPORT_HAS_DLL)
#  define TCOLLITRANSFER_EXPORT_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && TCOLLITRANSFER_EXPORT_HAS_DLL */

#if !defined (TCOLLITRANSFER_EXPORT_HAS_DLL)
#  define TCOLLITRANSFER_EXPORT_HAS_DLL 1
#endif /* ! TCOLLITRANSFER_EXPORT_HAS_DLL */

#if defined (TCOLLITRANSFER_EXPORT_HAS_DLL) && (TCOLLITRANSFER_EXPORT_HAS_DLL == 1)
#  if defined (TCOLLITRANSFER_EXPORT_BUILD_DLL)
#    define TColliTransfer_Export_Export ACE_Proper_Export_Flag
#    define TCOLLITRANSFER_EXPORT_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define TCOLLITRANSFER_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* TCOLLITRANSFER_EXPORT_BUILD_DLL */
#    define TColliTransfer_Export_Export ACE_Proper_Import_Flag
#    define TCOLLITRANSFER_EXPORT_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define TCOLLITRANSFER_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* TCOLLITRANSFER_EXPORT_BUILD_DLL */
#else /* TCOLLITRANSFER_EXPORT_HAS_DLL == 1 */
#  define TColliTransfer_Export_Export
#  define TCOLLITRANSFER_EXPORT_SINGLETON_DECLARATION(T)
#  define TCOLLITRANSFER_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* TCOLLITRANSFER_EXPORT_HAS_DLL == 1 */

// Set TCOLLITRANSFER_EXPORT_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (TCOLLITRANSFER_EXPORT_NTRACE)
#  if (ACE_NTRACE == 1)
#    define TCOLLITRANSFER_EXPORT_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define TCOLLITRANSFER_EXPORT_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !TCOLLITRANSFER_EXPORT_NTRACE */

#if (TCOLLITRANSFER_EXPORT_NTRACE == 1)
#  define TCOLLITRANSFER_EXPORT_TRACE(X)
#else /* (TCOLLITRANSFER_EXPORT_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define TCOLLITRANSFER_EXPORT_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (TCOLLITRANSFER_EXPORT_NTRACE == 1) */

#endif /* TCOLLITRANSFER_EXPORT_EXPORT_H */

// End of auto generated file.
